"""
formatter.py — formats RCA dict into markdown and terminal output
"""

from datetime import datetime


def format_markdown(rca: dict, context: dict) -> str:
    """
    Render the RCA dict as a structured markdown postmortem document.
    """
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines = []

    # Header
    title = rca.get("title", "Incident Postmortem")
    severity = rca.get("severity", "Unknown")
    lines += [
        f"# {title}",
        f"",
        f"| Field | Value |",
        f"|---|---|",
        f"| **Severity** | {severity} |",
        f"| **Start** | {context['start_time']} |",
        f"| **End** | {context['end_time']} |",
        f"| **Duration** | {context['duration_minutes']} minutes |",
        f"| **Alert** | {context['alert']} |",
        f"| **Log Group** | `{context['log_group']}` |",
        f"| **Generated** | {now} |",
        f"",
    ]

    # Summary
    lines += [
        "## Summary",
        "",
        rca.get("summary", "_No summary generated._"),
        "",
    ]

    # Impact
    lines += [
        "## Impact",
        "",
        rca.get("impact", "_Unknown_"),
        "",
    ]

    # Root Cause
    lines += [
        "## Root Cause",
        "",
        rca.get("root_cause", "_Could not determine root cause from available data._"),
        "",
    ]

    # Deploy Correlation
    deploy_correlation = rca.get("deploy_correlation")
    if deploy_correlation:
        lines += [
            "## Deploy Correlation",
            "",
            deploy_correlation,
            "",
        ]

    # Contributing Factors
    factors = rca.get("contributing_factors", [])
    if factors:
        lines += ["## Contributing Factors", ""]
        for f in factors:
            lines.append(f"- {f}")
        lines.append("")

    # Timeline
    timeline = rca.get("timeline", [])
    if timeline:
        lines += ["## Timeline", ""]
        for event in timeline:
            lines.append(f"- **{event.get('time', '')}** — {event.get('event', '')}")
        lines.append("")

    # Hypotheses (if root cause uncertain)
    hypotheses = rca.get("hypotheses", [])
    if hypotheses:
        lines += ["## Alternative Hypotheses", ""]
        for h in hypotheses:
            lines.append(f"- {h}")
        lines.append("")

    # Action Items
    action_items = rca.get("action_items", [])
    if action_items:
        lines += [
            "## Action Items",
            "",
            "| Priority | Action | Owner |",
            "|---|---|---|",
        ]
        for item in action_items:
            priority = item.get("priority", "medium")
            action = item.get("action", "")
            owner = item.get("owner", "TBD")
            lines.append(f"| {priority.upper()} | {action} | {owner} |")
        lines.append("")

    # Footer
    lines += [
        "---",
        "",
        "_Generated by [logmortem](https://github.com/sezgiozrn/Logmortem)_",
        "",
    ]

    return "\n".join(lines)


def print_summary(context: dict) -> None:
    """
    Print a human-readable summary of collected context to terminal.
    Used in --dry-run mode.
    """
    print(f"  Log Group:       {context['log_group']}")
    print(f"  Start:           {context['start_time']}")
    print(f"  End:             {context['end_time']}")
    print(f"  Duration:        {context['duration_minutes']} minutes")
    print(f"  Alert:           {context['alert']}")
    print(f"  Log Events:      {context['total_log_events']} total, "
          f"{context['error_log_count']} errors")
    print()

    if context.get("error_logs"):
        print("  TOP ERROR LOGS:")
        for e in context["error_logs"][:5]:
            print(f"    [{e['timestamp']}] {e['message'][:120]}")
        print()

    if context.get("deploys"):
        print("  RECENT DEPLOYS:")
        for d in context["deploys"][:5]:
            print(f"    [{d['time']}] {d['workflow']} — "
                  f"{d['status']} (commit {d['commit']}: {d['commit_message'][:60]})")
        print()
    else:
        print("  DEPLOYS: None collected\n")
